zelazowy_memcached_homepage:
    pattern:  /
    defaults: { _controller: ZelazowyMemcachedBundle:Memcached:index }

zelazowy_memcached_new:
    pattern: /new
    defaults:
        _controller: ZelazowyMemcachedBundle:Memcached:new